FROM m3958/base:201401
MAINTAINER Libo Jiang <jianglibo@gmail.com>

RUN yum -y install \
    php \
    php-fpm \
    php-gd \
    php-pear \
    php-mysql \
    php-mcrypt \
    php-xcache \
    php-xml \
    php-xmlrpc \
    php-mbstring \
    php-curl

EXPOSE 80
