FROM m3958/base:201401
MAINTAINER Libo Jiang <jianglibo@gmail.com>

RUN curl -o piwikroot.zip http://upload.fh.gov.cn/5jsNsrK.zip
RUN unzip piwikroot.zip
RUN rm -f piwikroot.zip 
RUN mv piwik piwikroot
