FROM m3958/base:201401
MAINTAINER Libo Jiang <jianglibo@gmail.com>
 
RUN curl -L -o /usr/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
RUN chmod +x /usr/bin/lein

RUN /usr/bin/lein
